// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetMapManager.API.Data;

#nullable disable

namespace NetMapManager.API.Migrations
{
    [DbContext(typeof(NetMapDbContext))]
    partial class NetMapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetMapManager.API.Models.AuthorizedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DomainUsername")
                        .IsUnique();

                    b.ToTable("AuthorizedUsers");
                });

            modelBuilder.Entity("NetMapManager.API.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatchCordType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("NetMapManager.API.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationPortType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationSwitchId")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePortType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceSwitchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationSwitchId");

                    b.HasIndex("SourceSwitchId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("NetMapManager.API.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SwitchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwitchId");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("NetMapManager.API.Models.NetworkSwitch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedVlans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentSwitchId")
                        .HasColumnType("int");

                    b.Property<double>("PhysicalX")
                        .HasColumnType("float");

                    b.Property<double>("PhysicalY")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SwitchModelId")
                        .HasColumnType("int");

                    b.Property<int>("TotalPorts")
                        .HasColumnType("int");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("float");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParentSwitchId");

                    b.HasIndex("SwitchModelId");

                    b.ToTable("NetworkSwitches");
                });

            modelBuilder.Entity("NetMapManager.API.Models.SwitchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SwitchModels");
                });

            modelBuilder.Entity("NetMapManager.API.Models.VlanDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subnet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VlanDefinitions");
                });

            modelBuilder.Entity("NetMapManager.API.Models.Link", b =>
                {
                    b.HasOne("NetMapManager.API.Models.NetworkSwitch", "DestinationSwitch")
                        .WithMany()
                        .HasForeignKey("DestinationSwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NetMapManager.API.Models.NetworkSwitch", "SourceSwitch")
                        .WithMany()
                        .HasForeignKey("SourceSwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationSwitch");

                    b.Navigation("SourceSwitch");
                });

            modelBuilder.Entity("NetMapManager.API.Models.MaintenanceLog", b =>
                {
                    b.HasOne("NetMapManager.API.Models.NetworkSwitch", "Switch")
                        .WithMany()
                        .HasForeignKey("SwitchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Switch");
                });

            modelBuilder.Entity("NetMapManager.API.Models.NetworkSwitch", b =>
                {
                    b.HasOne("NetMapManager.API.Models.NetworkSwitch", "ParentSwitch")
                        .WithMany("ChildSwitches")
                        .HasForeignKey("ParentSwitchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetMapManager.API.Models.SwitchModel", "SwitchModel")
                        .WithMany("Switches")
                        .HasForeignKey("SwitchModelId");

                    b.Navigation("ParentSwitch");

                    b.Navigation("SwitchModel");
                });

            modelBuilder.Entity("NetMapManager.API.Models.NetworkSwitch", b =>
                {
                    b.Navigation("ChildSwitches");
                });

            modelBuilder.Entity("NetMapManager.API.Models.SwitchModel", b =>
                {
                    b.Navigation("Switches");
                });
#pragma warning restore 612, 618
        }
    }
}
